### PR TITLE
chore: major version updates for Ginkgo and Lager

### PR DESCRIPTION
**Pull request by blgm**
- bumps to Ginkgo v2
- bumps to Lager v3
- drops the vendor directory as it's not needed (Go will download the right things when needed)

### CODE REVIEW

**Comment by MarcPaquette** [comment]
Hi @blgm,

Can you resolve the conflicts for this issue and we can get this merged in. 

Thanks,
@MarcPaquette

**Comment by MarcPaquette** [comment]
Hi @blgm, 
Are you able to resolve these conflicts?
Thanks!

**Comment by MarcPaquette** [comment]
Hi @blgm,

Thanks for the contribution!  Are you able to resolve the conflicts for the PR?  We're trying to tidy up our inbox and we may need to close out this outstanding PR if it is left inactive.

Thanks
@MarcPaquette

**Comment by blgm** [comment]
Hi @MarcPaquette. Sorry for my slow response. I've resolved the conflicts. My context on this is a little hazy, but I think the intention was just to update to new dependencies.

**Review by MarcPaquette — APPROVED** [review]
Changes LGTM! Thanks!

**Pull request merged**
